CREATE TABLE `donate_unitpay` (
  `id` int(11) NOT NULL,
  `data` datetime NOT NULL,
  `operator` varchar(20) NOT NULL DEFAULT '',
  `paymentType` varchar(20) NOT NULL DEFAULT '',
  `phone` varchar(50) NOT NULL DEFAULT '',
  `out_summ` float(16,2) NOT NULL DEFAULT '0.00',
  `profit` float(16,2) NOT NULL DEFAULT '0.00',
  `unitpayId` int(11) NOT NULL DEFAULT '0',
  `don_kurs` float(16,2) NOT NULL DEFAULT '1',
  `money` int(11) NOT NULL DEFAULT '0',
  `act_bonus` int(11) NOT NULL DEFAULT '0',
  `bonus_money` int(11) NOT NULL DEFAULT '0',
  `login` varchar(25) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `userid` int(11) NOT NULL DEFAULT '0',
  `ip` varchar(15) NOT NULL DEFAULT '',
  `serv` int(11) NOT NULL DEFAULT '1',
  `status` int(11) NOT NULL DEFAULT '0',
  `errMsg` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `donate_unitpay`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `donate_unitpay`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `donate_unitpay` ADD INDEX(`status`);

ALTER TABLE `donate_unitpay` ADD INDEX(`data`);

CREATE TABLE IF NOT EXISTS `online_stat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `data` datetime NOT NULL,
  `online_acc` int(11) NOT NULL,
  `online_pers` int(11) NOT NULL,
  `online_world` int(11) NOT NULL,
  `online_instance` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `shop_icons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `icon` blob NOT NULL,
  UNIQUE KEY `name` (`name`),
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

CREATE TABLE `donate_freekassa` (
  `id` int(11) NOT NULL,
  `data` datetime NOT NULL,
  `currency_id` int(11) NOT NULL DEFAULT '0',
  `email` varchar(45) NOT NULL DEFAULT '',
  `out_summ` float(16,2) NOT NULL,
  `intid` int(11) NOT NULL DEFAULT '0',
  `don_kurs` float(16,2) NOT NULL,
  `money` int(11) NOT NULL,
  `act_bonus` int(11) NOT NULL,
  `bonus_money` int(11) NOT NULL,
  `login` varchar(25) CHARACTER SET utf8 NOT NULL,
  `userid` int(11) NOT NULL,
  `ip` varchar(15) NOT NULL,
  `serv` int(11) NOT NULL DEFAULT '1',
  `status` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `donate_freekassa`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `donate_freekassa`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `donate_freekassa` ADD INDEX(`status`);

ALTER TABLE `donate_freekassa` ADD INDEX(`data`);

CREATE TABLE `config` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'int',
  `value` text CHARACTER SET utf8 NOT NULL,
  `section` int(11) NOT NULL DEFAULT '0',
  `group` int(11) NOT NULL DEFAULT '0',
  `desc` text CHARACTER SET utf8 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `config`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `config`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

INSERT INTO `config` (`name`, `type`, `value`, `section`, `group`, `desc`) VALUES
('lk_active_for_all', 'bool', '1', 0, 0, 'Открыть / закрыть функции ЛК для всех кроме админов'),
('server_side_script_path', 'string', 'http://localhost/lkab/', 0, 0, 'Путь к папке со скриптами сервер части'),
('auth_type', 'int', '2', 0, 0, 'Способ хранения паролей аккаунтов (используется для авторизации и регистрации):\r\n	1 - binary MD5, пример: <font color=\"#0000ff\">åÅÍOXÖööëtRúýèk</font>\r\n	2 - 0xMD5, пример: <font color=\"#0000ff\">0x671298fb29179832ab3912</font>\r\n	3 - base64(MD5), пример: <font color=\"#0000ff\">w6XDhcONT1jDlsO2FcO2w6t0UsO6w73DqGs=</font>'),
('email_require', 'bool', '0', 0, 0, 'Требовать E-mail для авторизации в ЛК'),
('email_require_change', 'bool', '1', 0, 0, 'Требовать E-mail для смены пароля'),
('answer_require_change', 'bool', '1', 0, 0, 'Требовать Ответ на вопрос для смены пароля'),
('email_confirm', 'bool', '1', 1, 0, 'Требовать подтверждения E-mail при регистрации'),
('ip_max_reg', 'int', '2', 1, 0, 'Ограничение кол-ва регистрации аккаунтов на один IP (0 - без ограничений)'),
('email_max_reg', 'int', '0', 1, 0, 'Ограничение кол-ва регистрации аккаунтов на один EMail (0 - без ограничений)'),
('login_filter', 'string', '/[^0-9a-z_]/', 1, 0, 'Фильтр символов для логина'),
('login_min_len', 'int', '3', 1, 0, 'Минимальное количество символов для логина'),
('login_max_len', 'int', '20', 1, 0, 'Максимальное количество символов для логина'),
('check_rus', 'string', '/^[a-zA-Zа-яА-ЯёЁ0-9\\-\\+_ ]+$/u', 1, 0, 'Фильтр для вопроса/ответа при регистрации и смене пароля'),
('passw_filter', 'string', '/[^0-9a-zA-Z\\-\\+_ ]/', 1, 0, 'Фильтр символов для пароля'),
('passw_min_len', 'int', '6', 1, 0, 'Минимальное количество символов для пароля'),
('passw_max_len', 'int', '20', 1, 0, 'Максимальное количество символов для пароля'),
('quest_template', 'arraystring', 'Ваше любимое блюдо,Девичья фамилия матери,Любимое число,Название любимой книги,Ваш любимый писатель,Кличка животного,Номер телефона,Имя Вашей первой учительницы,Имя и отчество Вашей бабушки,Модель первой машины,Номер телефона друга', 1, 0, 'Список вопросов для регистрации (разделитель запятая без пробелов, длина вопроса не более 25 символов)'),
('rules_link', 'string', 'http://localhost/rules.php/', 1, 0, 'Ссылка на страницу с правилами проекта'),
('cookie_pasw', 'string', 'GnlweumrfYtbf2fnYN917', 0, 0, 'Пароль для шифрования данных'),
('encoder_Salt', 'string', 'dFEmuwef342', 0, 0, 'Добавочный код для шифрования (соль)'),
('cookie_name', 'string', 'RememberLK', 0, 0, 'Название переменной в cookies'),
('title', 'string', 'Личный кабинет - MyServ', 0, 0, 'Титул страницы'),
('description', 'string', 'Личный кабинет сервера MyServ', 0, 0, 'Описание'),
('uploaddir', 'string', 'uploads', 0, 0, 'Папка для загрузки значков клана игроками'),
('admin_email', 'string', 'support@myserv.net', 5, 0, 'Почта, указываемая для ответа при отправки письма при смене пароля и т.п.'),
('tp2world_enable', 'bool', '1', 2, 0, 'Разрешить телепорт из данжа в мир'),
('tp2worldcost', 'cost', '0|0', 2, 0, 'Стоимость телепорта из данжа в мир'),
('fixsp_enable', 'bool', '1', 2, 1, 'Разрешить вывод духа из минуса'),
('fixspcost', 'cost', '0|0', 2, 1, 'Стоимость вывода духа из минуса'),
('fixexp_enable', 'bool', '1', 2, 2, 'Разрешить вывод опыта из минуса'),
('fixexpcost', 'cost', '0|0', 2, 2, 'Стоимость вывода опыта из минуса'),
('klancost', 'cost', '10|0', 2, 12, 'Стоимость установки значка клана'),
('klan_pic_size', 'int', '16', 2, 12, 'Размер значка клану в пикселях'),
('chname_enable', 'bool', '1', 2, 3, 'Разрешить смену создателя оружия, брони и бижутерии'),
('chnamecost', 'cost', '10|0', 2, 3, 'Стоимость смены создателя'),
('name_maxlength', 'int', '12', 2, 3, 'Макс. символов в новом нике создателя вещи (для версии сервера 1.3.6 ставьте не больше 10)'),
('nullbankpass_enable', 'bool', '1', 2, 4, 'Разрешить сброс пароля от банка'),
('nullbankpass', 'cost', '25|0', 2, 4, 'Стоимость обнуления пароля банка'),
('unbind_enable', 'bool', '1', 2, 5, 'Разрешить отвязку вещей (стоимость указывается в файле config_db.php)'),
('proctype_list', 'arrayint', '32791,32799', 2, 5, 'Список с масками предметов, которые можно будет отвязать в разделе персонажи (разделитель запятая без пробелов)'),
('allow_lk2game', 'bool', '0', 2, 9, 'Разрешить вывод лк монет в игру (голд шоп)'),
('allow_lk_transfer', 'bool', '1', 2, 0, 'Разрешить перевод ЛК монет на другой аккаунт'),
('allow_lk_gold_exchange', 'bool', '0', 2, 6, 'Разрешить обмен игровых ресурсов на ЛК голд'),
('gold_itemid', 'itemid', '55176', 2, 6, 'ID игрового итема для обмена на ЛК голд'),
('gold_item_exchange_rate', 'int', '1', 2, 6, 'Курс обмена итемов на ЛК голд, 1 ЛК голд = n items'),
('allow_lk_silver_exchange', 'bool', '0', 2, 7, 'Разрешить обмен игровых ресурсов на ЛК серебро'),
('silver_itemid', 'itemid', '11208', 2, 7, 'ID игрового итема для обмена на ЛК серебро'),
('silver_item_exchange_rate', 'int', '3', 2, 7, 'Курс обмена итемов на ЛК серебро, 1 ЛК серебро = n items'),
('lk_transfer_min_role_lvl', 'int', '0', 2, 0, 'Минимальный уровень персонажа на аккаунте, для возможности перевода ЛК монет на другой аккаунт\r\n	0 - отключить требование'),
('lk_transfer_vk_only', 'bool', '0', 2, 0, 'Разрешить перевод ЛК монет на другой аккаунт, только если привязана учетка VK'),
('lk_transfer_steam_only', 'bool', '0', 2, 0, 'Разрешить перевод ЛК монет на другой аккаунт, только если привязана учетка STEAM'),
('servid', 'int', '1', 0, 0, 'ID сервера в serverlist.txt (для значков клана, доната и т.п.)'),
('default_icon_num', 'int', '0', 0, 0, 'Номер иконки по умолчанию (для значков клана)'),
('favicon', 'string', 'img/favicon.ico', 0, 0, 'Иконка сайта'),
('logo', 'string', 'img/logo20.png', 0, 0, 'Логитип'),
('logotext', 'string', 'MyServ', 0, 0, 'Название сервера в логотипе'),
('cite_link', 'string', 'http://myserv.net', 0, 0, 'Ссылка на сайт'),
('contacts', 'text', '<img src=\"img/skype32.png\" border=0> <strong>myserv</strong>', 0, 0, 'HMTM код с контактами'),
('cron_act_passw', 'string', 'FEnouicvmHNJGvr73nW', 0, 0, 'Пароль для вызова скриптов, запускаемых через Cron. Обязательно поменяйте после установки ЛК!'),
('mmotop_link', 'string', '', 0, 0, 'Ссылка на голосование в MMOTOP'),
('qtop_link', 'string', '', 0, 0, 'Ссылка на голосование в Q-TOP'),
('act_bonus', 'int', '0', 3, 0, 'Текущий бонус к донату в %'),
('don_kurs', 'float', '3', 3, 0, 'Множитель расчета монет сумма = монеты * множитель'),
('donate_system', 'select', 'Disabled,UnitPay,Free-Kassa,1', 3, 0, 'Используемая платежная система для доната, Disabled - для отключения доната'),
('accumulation_system', 'bool', '1', 3, 0, 'Использовать накопительную систему (бонусы, зависимые от суммы всех платежей)'),
('acc_param', 'arraylist', 'a:9:{i:0;s:1:\"0\";i:500;s:1:\"1\";i:1000;s:1:\"3\";i:3000;s:1:\"5\";i:5000;s:1:\"7\";i:10000;s:2:\"10\";i:15000;s:2:\"13\";i:20000;s:2:\"16\";i:30000;s:2:\"20\";}', 3, 0, 'Параметры накопительной системы:\r\nсумма-бонус\r\nсумма-бонус\r\nи т.п.\r\n\r\nсумма в руб, бонус в %'),
('bonus_system', 'bool', '1', 3, 0, 'Использовать бонусную систему (бонусы, зависимые от суммы единоразового платежа)'),
('bonus_param', 'arraylist', 'a:4:{i:500;s:1:\"3\";i:1000;s:1:\"7\";i:3000;s:2:\"10\";i:5000;s:2:\"15\";}', 3, 0, 'Параметры бонусной системы:\r\nсумма-бонус\r\nсумма-бонус\r\nи т.п.\r\n\r\nсумма в руб, бонус в %'),
('', 'desc', 'Бонусный итем при донате', 3, 0, ''),
('send_bonus_item', 'bool', '1', 3, 0, 'Отправлять бонусный итем при донате'),
('bonus_id', 'itemid', '12979', 3, 0, 'Параметры бонусного итема'),
('bonus_count', 'int', '20', 3, 0, 'Количество'),
('bonus_max_count', 'int', '1000', 3, 0, 'Количество в ячейке'),
('bonus_data', 'string', '', 3, 0, 'Октет'),
('bonus_proctype', 'proctype', '0', 3, 0, 'Привязка'),
('bonus_expire', 'int', '0', 3, 0, 'Срок действия итема в секундах (если 0 - вечный)'),
('bonus_mask', 'mask', '0', 3, 0, 'Маска'),
('max_votes_from_ip', 'int', '2', 4, 0, 'Максимум голосов в сутки с одного айпи'),
('max_votes_from_login', 'int', '2', 4, 0, 'Максимум голосов в сутки на один логин'),
('num_day_process', 'int', '2', 4, 0, 'Количество обрабатываемых дней (будут обрабатываться только голоса давностью не более num дней)'),
('top_bonus_vk_only', 'bool', '0', 4, 0, 'Выдавать бонус за голосование только на аккаунты с привязанным VK'),
('top_bonus_steam_only', 'bool', '0', 4, 0, 'Выдавать бонус за голосование только на аккаунты с привязанным Steam'),
('', 'desc', 'Настройка бонусов за голосование в MMOTOP', 4, 1, ''),
('mmotop_statlink', 'string', '', 4, 1, 'Ссылка на статистику голосов MMOTOP'),
('mmotop_cost1', 'cost', '0|0', 4, 1, 'Стоимость обычного голоса'),
('mmotop_cost2', 'cost', '0|0', 4, 1, 'Стоимость SMS голоса (10 голосов)'),
('mmotop_cost3', 'cost', '0|0', 4, 1, 'Стоимость SMS голоса (50 голосов)'),
('mmotop_cost4', 'cost', '0|0', 4, 1, 'Стоимость SMS голоса (100 голосов)'),
('send_mmotop_message', 'bool', '1', 4, 1, 'Отправлять сообщение в ГМ чат после выдачи бонусов'),
('mmotop_message', 'string', '%d игроков только что получили бонусы за голосование в mmotop. Поддержи проект - получи бонус!', 4, 1, 'Сообщение в ГМ чат после выдачи бонусов'),
('send_mmotop_bonusitem', 'bool', '0', 4, 1, 'Отправлять предмет за голосование'),
('', 'desc', 'Параметры бонусного итема за обычный голос MMOTOP', 4, 1, ''),
('mmotop1_itemid', 'itemid', '0', 4, 1, ''),
('mmotop1_count', 'int', '0', 4, 1, ''),
('mmotop1_maxcount', 'int', '0', 4, 1, ''),
('mmotop1_data', 'string', '', 4, 1, ''),
('mmotop1_proctype', 'proctype', '0', 4, 1, ''),
('mmotop1_expire', 'int', '0', 4, 1, 'Срок действия итема в секундах (если 0 - вечный)'),
('mmotop1_mask', 'mask', '0', 4, 1, ''),
('', 'desc', 'Параметры бонусного итема за SMS (10) голосов MMOTOP', 4, 1, ''),
('mmotop2_itemid', 'itemid', '12979', 4, 1, ''),
('mmotop2_count', 'int', '20', 4, 1, ''),
('mmotop2_maxcount', 'int', '1000', 4, 1, ''),
('mmotop2_data', 'string', '', 4, 1, ''),
('mmotop2_proctype', 'proctype', '0', 4, 1, ''),
('mmotop2_expire', 'int', '0', 4, 1, 'Срок действия итема в секундах (если 0 - вечный)'),
('mmotop2_mask', 'mask', '0', 4, 1, ''),
('', 'desc', 'Параметры бонусного итема за SMS (50) голосов MMOTOP', 4, 1, ''),
('mmotop3_itemid', 'itemid', '0', 4, 1, ''),
('mmotop3_count', 'int', '0', 4, 1, ''),
('mmotop3_maxcount', 'int', '0', 4, 1, ''),
('mmotop3_data', 'string', '', 4, 1, ''),
('mmotop3_proctype', 'int', '0', 4, 1, ''),
('mmotop3_expire', 'int', '0', 4, 1, 'Срок действия итема в секундах (если 0 - вечный)'),
('mmotop3_mask', 'int', '0', 4, 1, ''),
('', 'desc', 'Параметры бонусного итема за SMS (100) голосов MMOTOP', 4, 1, ''),
('mmotop4_itemid', 'itemid', '0', 4, 1, ''),
('mmotop4_count', 'int', '0', 4, 1, ''),
('mmotop4_maxcount', 'int', '0', 4, 1, ''),
('mmotop4_data', 'string', '', 4, 1, ''),
('mmotop4_proctype', 'int', '0', 4, 1, ''),
('mmotop4_expire', 'int', '0', 4, 1, 'Срок действия итема в секундах (если 0 - вечный)'),
('mmotop4_mask', 'int', '0', 4, 1, ''),
('', 'desc', 'Настройка бонусов за голосование в Q-TOP', 4, 2, ''),
('qtop_statlink', 'string', '', 4, 2, 'Ссылка на статистику голосов Q-TOP'),
('qtop_cost1', 'cost', '3|0', 4, 2, 'Стоимость обычного голоса'),
('qtop_cost2', 'cost', '5|0', 4, 2, 'Стоимость SMS голоса'),
('send_qtop_message', 'bool', '1', 4, 2, 'Отправлять сообщение в ГМ чат после выдачи бонусов'),
('qtop_message', 'string', '%d игроков только что получили бонусы за голосование в Q-Top. Поддержи проект - получи бонус!', 4, 2, 'Сообщение в ГМ чат после выдачи бонусов'),
('send_qtop_bonusitem', 'bool', '0', 4, 2, 'Отправлять предмет за голосование'),
('', 'desc', 'Параметры бонусного итема за обычный голос Q-TOP', 4, 2, ''),
('qtop1_itemid', 'itemid', '12979', 4, 2, ''),
('qtop1_count', 'int', '20', 4, 2, ''),
('qtop1_maxcount', 'int', '1000', 4, 2, ''),
('qtop1_data', 'string', '', 4, 2, ''),
('qtop1_proctype', 'proctype', '0', 4, 2, ''),
('qtop1_expire', 'int', '0', 4, 2, 'Срок действия итема в секундах (если 0 - вечный)'),
('qtop1_mask', 'mask', '0', 4, 2, ''),
('', 'desc', 'Параметры бонусного итема за SMS голос Q-TOP', 4, 2, ''),
('qtop2_itemid', 'itemid', '12979', 4, 2, ''),
('qtop2_count', 'int', '20', 4, 2, ''),
('qtop2_maxcount', 'int', '1000', 4, 2, ''),
('qtop2_data', 'string', '', 4, 2, ''),
('qtop2_proctype', 'proctype', '0', 4, 2, ''),
('qtop2_expire', 'int', '0', 4, 2, 'Срок действия итема в секундах (если 0 - вечный)'),
('qtop2_mask', 'mask', '0', 4, 2, ''),
('', 'desc', 'Параметры хранения логов голосования', 4, 3, ''),
('top_log_lifetime', 'int', '0', 4, 3, 'Срок хранения логов выдачи голосования в месяцах (0 - не чистить лог)'),
('zoneid', 'int', '1', 0, 0, 'Параметр zoneid сервера (используется для нескольких серверов на одной базе аккаунтов)'),
('aid', 'int', '1', 0, 0, 'Параметр aid сервера (используется для нескольких серверов на одной базе аккаунтов)'),
('', 'desc', 'Параметры сервиса UnitPay', 3, 1, ''),
('unitpay_id', 'int', '0', 3, 1, 'ID проекта в системе UnitPay'),
('unitpay_secret_key', 'string', '', 3, 1, 'Секретный ключ проекта в системе UnitPay'),
('unitpay_form_url', 'string', '', 3, 1, 'Ссылка формы оплаты проекта в системе UnitPay, например https://unitpay.ru/pay/1111-11111'),
('', 'desc', 'Параметры сервиса Free-Kassa', 3, 0, ''),
('freekassa_merchant_id', 'int', '0', 3, 0, 'ID проекта в системе FreeKassa'),
('freekassa_secret_word1', 'string', '', 3, 0, 'Секретное слово 1 в системе FreeKassa'),
('freekassa_secret_word2', 'string', '', 3, 0, 'Секретное слово 2 в системе FreeKassa'),
('register_gold', 'int', '0', 1, 1, 'Количество голда, выдаваемое после регистрации аккаунта (0 - не выдавать)'),
('register_active', 'bool', '1', 1, 2, 'Включить/Выключить регистрацию аккаунтов'),
('get_gold_btn', 'bool', '0', 1, 1, 'Выдавать стартовый голд по запросу через личный кабинет (рекомендуется использовать этот способ)'),
('', 'desc', 'Настройки реферальной системы', 1, 3, ''),
('ref_don_bonus_enable', 'bool', '0', 1, 3, 'Выдавать % от доната за реферала'),
('ref_don_bonus', 'float', '5', 1, 3, 'Размер % от доната приглашенного (поддерживается дробное значение)'),
('ref_don_bonus_timeused', 'int', '360000', 1, 3, 'Кол-во секунд онлайн на приглашенном аккаунте, необходимых для получения % от доната'),
('ref_don_level_bonus_enabled', 'bool', '0', 1, 4, 'Выдавать предмет за получение уровня у персонажа на приглашенном аккаунте'),
('ref_require_level', 'int', '105', 1, 4, 'Уровень, который должен апнуть приглашенный игрок, для выдачи бонуса пригласившему'),
('ref_item_id', 'itemid', '0', 1, 4, 'Предмет за достижение уровня (выдается тому, кто пригласил)'),
('ref_item_count', 'int', '0', 1, 4, ''),
('ref_item_maxcount', 'int', '0', 1, 4, ''),
('ref_item_data', 'string', '0', 1, 4, ''),
('ref_item_proctype', 'proctype', '0', 1, 4, ''),
('ref_item_expire', 'int', '0', 1, 4, 'Срок действия итема в секундах (если 0 - вечный)'),
('ref_item_mask', 'mask', '0', 1, 4, ''),
('', 'desc', 'Авторизация через ВКонтакте <img src=\"img/vk_login.png\">', 1, 4, ''),
('vk_login_enable', 'bool', '0', 1, 4, 'Разрешить авторизацию через ВКонтакте'),
('vk_app_id', 'string', '', 1, 4, 'ID приложения ВКонтакте. Приложение можно <a href=\"https://vk.com/apps?act=manage\" target=\"_blank\">создать тут</a>'),
('vk_app_key', 'string', '', 1, 4, 'Ключ приложения ВКонтакте'),
('', 'desc', 'Авторизация через Steam <img src=\"img/steam_login.png\">', 1, 5, ''),
('steam_login_enable', 'bool', '0', 1, 5, 'Разрешить авторизацию через Steam'),
('steam_app_key', 'string', '', 1, 5, 'Ключ приложения Steam можно <a href=\"http://steamcommunity.com/dev/apikey\" target=\"_blank\">найти тут</a>'),
('lvlup_enable', 'bool', '0', 2, 8, 'Разрешить прокачку уровня в ЛК'),
('lvlup_maxlvl', 'int', '105', 2, 8, 'Максимальный уровень для прокачки в ЛК'),
('lvlup_100_cost', 'cost', '1', 2, 8, 'Стомость прокачки 1 уровня для уровней <=100'),
('lvlup_110_cost', 'cost', '1', 2, 8, 'Стомость прокачки 1 уровня для уровней от 101 до 110 включительно'),
('lvlup_120_cost', 'cost', '1', 2, 8, 'Стомость прокачки 1 уровня для уровней от 111 до 120 включительно'),
('lvlup_130_cost', 'cost', '1', 2, 8, 'Стомость прокачки 1 уровня для уровней от 121 до 130 включительно'),
('lvlup_140_cost', 'cost', '1', 2, 8, 'Стомость прокачки 1 уровня для уровней от 131 до 140 включительно'),
('lvlup_150_cost', 'cost', '1', 2, 8, 'Стомость прокачки 1 уровня для уровней от 141 до 150 включительно'),
('lvlup_150_plus', 'cost', '1', 2, 8, 'Стомость прокачки 1 уровня для уровней >150'),
('lk2game_exchange_rate', 'float', '1', 2, 9, 'Курс обмена ЛК на голд, 1 ЛК = n голда (поддерживаются дробные значения с отсеканием дробной части)'),
('', 'desc', 'Создание ячеек в броне и оружии', 2, 10, ''),
('add_slot_enable', 'bool', '0', 2, 10, 'Разрешить создание ячеек'),
('weapon_max_slot', 'select', '0,1,2,3,4,0', 2, 10, 'Максимальное количество ячеек в оружии'),
('armor_max_slot', 'select', '0,1,2,3,4,0', 2, 10, 'Максимальное количество ячеек в броне'),
('weapon_slot1_cost', 'cost', '1|0', 2, 10, 'Стоимость первой ячейки в оружии'),
('weapon_slot2_cost', 'cost', '2|0', 2, 10, 'Стоимость второй ячейки в оружии'),
('weapon_slot3_cost', 'cost', '3|0', 2, 10, 'Стоимость третьей ячейки в оружии'),
('weapon_slot4_cost', 'cost', '4|0', 2, 10, 'Стоимость четвертой ячейки в оружии'),
('armor_slot1_cost', 'cost', '1|0', 2, 10, 'Стоимость первой ячейки в броне'),
('armor_slot2_cost', 'cost', '2|0', 2, 10, 'Стоимость второй ячейки в броне'),
('armor_slot3_cost', 'cost', '3|0', 2, 10, 'Стоимость третьей ячейки в броне'),
('armor_slot4_cost', 'cost', '4|0', 2, 10, 'Стоимость четвертой ячейки в броне'),
('', 'desc', 'Увеличение дальности оружия', 2, 11, ''),
('add_distance_enable', 'bool', '0', 2, 11, 'Разрешить увеличение дальности'),
('add_distance_classes', 'arraystring', '1,5,9,13,182,291,292,23749,25333', 2, 11, 'Список классов оружия, на которых можно будет менять дальность\r\n	1 - Мечи\r\n	5 - Копья\r\n	9 - Топоры/молоты\r\n	13 - Оружие дальнего боя\r\n	182 - Кастеты\r\n	291 - Бич\r\n	292 - Магическое оружие\r\n	23749 - Кинжалы\r\n	25333 - Магическая сфера'),
('add_distance_max', 'int', '3', 2, 11, 'Максимальная дальность'),
('add_distance_cost', 'cost', '25|0', 2, 11, 'Стоимость увеличения дальности оружия до максимальной'),
('icons_type', 'select', 'MySQL,Files,1', 0, 0, 'Способ хранения и вывода иконок (в базе MysQL или в отдельных файлах)'),
('enable_ip_flags', 'bool', '0', 0, 0, 'Отображать флаги стран рядом с IP адресом (нужен установленный php-geoip или php5-geoip и geoip-database на хосте сервер части)'),
('promo_enabled', 'bool', '0', 0, 0, 'Включить возможность ввода промо кодов и получения за них бонусов. Список и награда за промо коды в таблице <b>promo_codes</b> сервер сайда.'),
('show_result', 'bool', '0', 0, 0, 'Вывод ответов сервера (<b>DEBUG</b>), используется для отладки и поиска ошибок. <b>\r\nБудет виден только администраторам (с соотв ID или IP из конфига)</b>'),
('mail_type', 'select', 'PhpMail,SMTP,0', 5, 0, 'Способ отправки почты'),
('', 'desc', 'Настройки SMTP', 5, 1, 'Актуально только при выбранном SMTP способе отправки почты'),
('smtp_host', 'string', 'smtp.yandex.ru', 5, 1, 'Cервер для отправки почты'),
('smtp_port', 'int', '587', 5, 1, 'Порт для отправки почты'),
('smtp_username', 'string', '', 5, 1, 'Имя пользователя на SMTP сервере'),
('smtp_password', 'password', '', 5, 1, 'Пароль пользователя на SMTP сервере'),
('smtp_from', 'string', 'Администрация', 5, 1, 'Ваше имя. Будет показывать при прочтении в поле \"От кого\"'),
('smtp_charset', 'string', 'UTF-8', 5, 1, 'Кодировка сообщений. Без надобности не трогать'),
('smtp_debug', 'select', '0,1,2,3,4,0', 5, 1, 'Вывод отладочной информации при отправке почты\r\n	0 - Без вывода отладочной информации\r\n	1 - Вывод комманд\r\n	2 - Вывод данных и комманд\r\n	3 - Вывод данных, комманд и статусов соединений\r\n	4 - Low-level data output'),
('smtp_logfile', 'string', 'logs/mail_log_1.log', 5, 1, 'Название файла логов для записи отладочной информации при отправке писем'),
('smtp_secure', 'select', '0,ssl,tls,2', 5, 1, 'Префикс безопасного соединения, <b>ssl</b>, <b>tls</b> или пустой.'),
('smtp_timeout', 'int', '60', 5, 1, 'Таймаут запроса в секундах'),
('', 'desc', 'Шаблоны писем', 5, 2, ''),
('reg_template', 'text', '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ru\">\r\n<head>\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n<style type=\"text/css\">\r\n    body {\r\n        font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\';\r\n        background-color: #f8fafc;\r\n        color: #74787e;\r\n        height: 100%;\r\n        hyphens: auto;\r\n        line-height: 1.4;\r\n        margin: 0;\r\n        -moz-hyphens: auto;\r\n        -ms-word-break: break-all;\r\n        width: 100% !important;\r\n        -webkit-hyphens: auto;\r\n        -webkit-text-size-adjust: none;\r\n        word-break: break-word;\r\n    }\r\n    p {\r\n        color: #3d4852; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;\r\n    }\r\n    table {\r\n        width: 100%;\r\n    }\r\n    table, td {\r\n        margin: 0; padding: 0;-premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;\r\n        box-sizing: border-box;\r\n    }\r\n    @media  only screen and (max-width: 600px) {\r\n        .inner-body {\r\n            width: 100% !important;\r\n        }\r\n\r\n        .footer {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n\r\n    @media  only screen and (max-width: 500px) {\r\n        .button {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n</style>\r\n</head>\r\n<body>\r\n<table class=\"wrapper\" style=\"background-color: #f8fafc\">\r\n    <tr>\r\n        <td align=\"center\">\r\n            <table class=\"content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n                <tr>\r\n                    <td class=\"header\" style=\"padding: 25px 0; text-align: center;\">\r\n                        <a href=\"#\" style=\"color: #bbbfc3; font-size: 19px; font-weight: bold; text-decoration: none; text-shadow: 0 1px 0 white;\">\r\n                            Добро пожаловать на сервер {SERVNAME}!\r\n                        </a>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td class=\"body\" width=\"100%\" style=\"background-color: #ffffff; border-bottom: 1px solid #edeff2; border-top: 1px solid #edeff2;\">\r\n                        <table class=\"inner-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; margin: 0 auto; width: 570px; -premailer-width: 570px;\">\r\n                            <tr>\r\n                                <td class=\"content-cell\" style=\"padding: 35px;\">\r\n                                    <h1 style=\"color: #3d4852; font-size: 19px; font-weight: bold; margin-top: 0; text-align: left;\">{NAME}, Ваш аккаунт успешно зарегистрирован</h1>\r\n                                    {ACT_TEMPLATE}\r\n                                    <p style=\"text-align: center;\">Данные вашего аккаунта:</p>\r\n                                    <table>\r\n                                        <tr>\r\n                                            <td style=\"width: 120px\" align=\"right\"> <font color=\"#aa0000\">Логин:</font></td>\r\n                                            <td align=\"left\"> <font color=\"#0000ff\">{LOGIN}</font></td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <td align=\"right\"> <font color=\"#aa0000\">Пароль:</font></td>\r\n                                            <td align=\"left\">{PASSW}</td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <td align=\"right\"> <font color=\"#aa0000\">Вопрос:</font></td>\r\n                                            <td align=\"left\">{QUESTION}</td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <td align=\"right\"> <font color=\"#aa0000\">Ответ:</font></td>\r\n                                            <td align=\"left\">{ANSWER}</td>\r\n                                        </tr>\r\n                                    </table>\r\n                                </td>\r\n                            </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td>\r\n                        <table class=\"footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; text-align: center; width: 570px;-premailer-width: 570px;\"><tr>\r\n                            <td class=\"content-cell\" align=\"center\" style=\"  padding: 35px;\">\r\n                                <p style=\"line-height: 1.5em; margin-top: 0; color: #aeaeae; font-size: 12px; text-align: center;\">© 2019 {SERVNAME}</p>\r\n                            </td>\r\n                        </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>', 5, 2, 'Письмо после регистрации аккаунта в HTML формате\r\n	{LOGIN} - логин аккаунта\r\n	{PASSW} - пароль аккаунта\r\n	{QUESTION} - Секретный вопрос\r\n	{ANSWER} - ответ на вопрос\r\n	{NAME} - имя\r\n	{ACT_TEMPLATE} - шаблон активации аккаунта\r\n	{REF_LINK} - реферальная ссылка\r\n	{SERVNAME} - Название сервера'),
('act_template', 'text', '<hr>\r\n                                    <p>Для начала игры, Вам нужно активировать аккаунт. Сделать это можно нажав на кнопку ниже</p>\r\n                                    <table class=\"action\" align=\"center\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 30px auto; padding: 0; text-align: center; width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;\">\r\n                                        <tr>\r\n                                            <td align=\"center\">\r\n                                                <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr>\r\n                                                    <td align=\"center\" style=\"text-align: center\">\r\n                                                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                                                            <tr>\r\n                                                                <td>\r\n                                                                    <a href=\"{ACT_LINK}\" class=\"button button-primary\" target=\"_blank\" style=\"  border-radius: 3px; box-shadow: 0 2px 3px rgba(0, 0, 0, 0.16); color: #fff; display: inline-block; text-decoration: none; -webkit-text-size-adjust: none; background-color: #3490dc; border-top: 10px solid #3490dc; border-right: 18px solid #3490dc; border-bottom: 10px solid #3490dc; border-left: 18px solid #3490dc;\">Активировать аккаунт</a>\r\n                                                                    <p style=\"color: #3d4852; line-height: 1.5em; margin-top: 20px; text-align: left; font-size: 12px;\">Если не получается нажать на кнопку, скопируйте эту ссылку в браузер<br><a href=\"{ACT_LINK}\" style=\"  color: #3869d4;\">{ACT_LINK}</a></p>\r\n                                                                </td>\r\n                                                            </tr>\r\n                                                        </table>\r\n                                                    </td>\r\n                                                </tr></table>\r\n                                            </td>\r\n                                        </tr>\r\n                                    </table>\r\n                                    <hr>', 5, 2, 'Текст активации аккаунта в HTML формате\r\n	{ACT_LINK} - ссылка для активации аккаунта'),
('reset_template', 'text', '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ru\">\r\n<head>\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n</head>\r\n<style type=\"text/css\">\r\n    body {\r\n        font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\';\r\n        background-color: #f8fafc;\r\n        color: #74787e;\r\n        height: 100%;\r\n        hyphens: auto;\r\n        line-height: 1.4;\r\n        margin: 0;\r\n        -moz-hyphens: auto;\r\n        -ms-word-break: break-all;\r\n        width: 100% !important;\r\n        -webkit-hyphens: auto;\r\n        -webkit-text-size-adjust: none;\r\n        word-break: break-word;\r\n    }\r\n    p {\r\n        color: #3d4852; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;\r\n    }\r\n    table {\r\n        width: 100%;\r\n    }\r\n    table, td {\r\n        margin: 0; padding: 0;-premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;\r\n        box-sizing: border-box;\r\n    }\r\n    @media  only screen and (max-width: 600px) {\r\n        .inner-body {\r\n            width: 100% !important;\r\n        }\r\n\r\n        .footer {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n\r\n    @media  only screen and (max-width: 500px) {\r\n        .button {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n</style>\r\n<body>\r\n<table class=\"wrapper\" style=\"background-color: #f8fafc\">\r\n    <tr>\r\n        <td align=\"center\">\r\n            <table class=\"content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n                <tr>\r\n                    <td class=\"header\" style=\"padding: 25px 0; text-align: center;\">\r\n                        <a href=\"#\" style=\"color: #bbbfc3; font-size: 19px; font-weight: bold; text-decoration: none; text-shadow: 0 1px 0 white;\">\r\n                            Сброс пароля от аккаунта на сервере {SERVNAME}!\r\n                        </a>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td class=\"body\" width=\"100%\" style=\"background-color: #ffffff; border-bottom: 1px solid #edeff2; border-top: 1px solid #edeff2;\">\r\n                        <table class=\"inner-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; margin: 0 auto; width: 570px; -premailer-width: 570px;\">\r\n                            <tr>\r\n                                <td class=\"content-cell\" style=\"padding: 35px;\">\r\n                                    <h1 style=\"color: #3d4852; font-size: 19px; font-weight: bold; margin-top: 0; text-align: left;\">Пароль был успешно изменен</h1>\r\n                                    <p>С айпи адреса {IP} был получен запрос на сброс пароля от аккаунта <b>{LOGIN}</b></p>\r\n                                    <p style=\"text-align: center;\">Данные вашего аккаунта:</p>\r\n                                    <table>\r\n                                        <tr>\r\n                                            <td style=\"width: 120px\" align=\"right\"> <font color=\"#aa0000\">Логин:</font></td>\r\n                                            <td align=\"left\"> <font color=\"#0000ff\">{LOGIN}</font></td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <td align=\"right\"> <font color=\"#aa0000\">Новый пароль:</font></td>\r\n                                            <td align=\"left\">{PASSW}</td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <td align=\"right\"> <font color=\"#aa0000\">Вопрос:</font></td>\r\n                                            <td align=\"left\">{QUESTION}</td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <td align=\"right\"> <font color=\"#aa0000\">Ответ:</font></td>\r\n                                            <td align=\"left\">{ANSWER}</td>\r\n                                        </tr>\r\n                                    </table>\r\n                                </td>\r\n                            </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td>\r\n                        <table class=\"footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; text-align: center; width: 570px;-premailer-width: 570px;\"><tr>\r\n                            <td class=\"content-cell\" align=\"center\" style=\"  padding: 35px;\">\r\n                                <p style=\"line-height: 1.5em; margin-top: 0; color: #aeaeae; font-size: 12px; text-align: center;\">© 2019 {SERVNAME}</p>\r\n                            </td>\r\n                        </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>', 5, 2, 'Письмо после сброса пароля аккаунта в HTML формате\r\n	{IP} - IP адрес с которого был сделан запрос\r\n	{LOGIN} - логин аккаунта\r\n	{PASSW} - новый пароль аккаунта\r\n	{QUESTION} - Секретный вопрос\r\n	{ANSWER} - ответ на вопрос\r\n	{SERVNAME} - Название сервера'),
('change_passw_template', 'text', '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ru\">\r\n<head>\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n</head>\r\n<style type=\"text/css\">\r\n    body {\r\n        font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\';\r\n        background-color: #f8fafc;\r\n        color: #74787e;\r\n        height: 100%;\r\n        hyphens: auto;\r\n        line-height: 1.4;\r\n        margin: 0;\r\n        -moz-hyphens: auto;\r\n        -ms-word-break: break-all;\r\n        width: 100% !important;\r\n        -webkit-hyphens: auto;\r\n        -webkit-text-size-adjust: none;\r\n        word-break: break-word;\r\n    }\r\n    p {\r\n        color: #3d4852; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;\r\n    }\r\n    table {\r\n        width: 100%;\r\n    }\r\n    table, td {\r\n        margin: 0; padding: 0;-premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;\r\n        box-sizing: border-box;\r\n    }\r\n    @media  only screen and (max-width: 600px) {\r\n        .inner-body {\r\n            width: 100% !important;\r\n        }\r\n\r\n        .footer {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n\r\n    @media  only screen and (max-width: 500px) {\r\n        .button {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n</style>\r\n<body>\r\n<table class=\"wrapper\" style=\"background-color: #f8fafc\">\r\n    <tr>\r\n        <td align=\"center\">\r\n            <table class=\"content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n                <tr>\r\n                    <td class=\"header\" style=\"padding: 25px 0; text-align: center;\">\r\n                        <a href=\"#\" style=\"color: #bbbfc3; font-size: 19px; font-weight: bold; text-decoration: none; text-shadow: 0 1px 0 white;\">\r\n                            Смена пароля от аккаунта на сервере {SERVNAME}!\r\n                        </a>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td class=\"body\" width=\"100%\" style=\"background-color: #ffffff; border-bottom: 1px solid #edeff2; border-top: 1px solid #edeff2;\">\r\n                        <table class=\"inner-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; margin: 0 auto; width: 570px; -premailer-width: 570px;\">\r\n                            <tr>\r\n                                <td class=\"content-cell\" style=\"padding: 35px;\">\r\n                                    <h1 style=\"color: #3d4852; font-size: 19px; font-weight: bold; margin-top: 0; text-align: left;\">Пароль был успешно изменен</h1>\r\n                                    <p>С айпи адреса {IP} был получен запрос на смену пароля от аккаунта <b>{LOGIN}</b></p>\r\n                                    <p style=\"text-align: center;\">Данные вашего аккаунта:</p>\r\n                                    <table>\r\n                                        <tr>\r\n                                            <td style=\"width: 120px\" align=\"right\"> <font color=\"#aa0000\">Логин:</font></td>\r\n                                            <td align=\"left\"> <font color=\"#0000ff\">{LOGIN}</font></td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <td align=\"right\"> <font color=\"#aa0000\">Новый пароль:</font></td>\r\n                                            <td align=\"left\">{PASSW}</td>\r\n                                        </tr>                                        \r\n                                    </table>\r\n                                </td>\r\n                            </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td>\r\n                        <table class=\"footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; text-align: center; width: 570px;-premailer-width: 570px;\"><tr>\r\n                            <td class=\"content-cell\" align=\"center\" style=\"  padding: 35px;\">\r\n                                <p style=\"line-height: 1.5em; margin-top: 0; color: #aeaeae; font-size: 12px; text-align: center;\">© 2019 {SERVNAME}</p>\r\n                            </td>\r\n                        </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>', 5, 2, 'Письмо после смены пароля аккаунта в HTML формате\r\n	{IP} - IP адрес с которого был сделан запрос\r\n	{LOGIN} - логин аккаунта\r\n	{PASSW} - новый пароль аккаунта\r\n	{SERVNAME} - Название сервера'),
('rem_ip_process_template', 'text', '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ru\">\r\n<head>\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n</head>\r\n<style type=\"text/css\">\r\n    body {\r\n        font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\';\r\n        background-color: #f8fafc;\r\n        color: #74787e;\r\n        height: 100%;\r\n        hyphens: auto;\r\n        line-height: 1.4;\r\n        margin: 0;\r\n        -moz-hyphens: auto;\r\n        -ms-word-break: break-all;\r\n        width: 100% !important;\r\n        -webkit-hyphens: auto;\r\n        -webkit-text-size-adjust: none;\r\n        word-break: break-word;\r\n    }\r\n    p {\r\n        color: #3d4852; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;\r\n    }\r\n    table {\r\n        width: 100%;\r\n    }\r\n    table, td {\r\n        margin: 0; padding: 0;-premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;\r\n        box-sizing: border-box;\r\n    }\r\n    @media  only screen and (max-width: 600px) {\r\n        .inner-body {\r\n            width: 100% !important;\r\n        }\r\n\r\n        .footer {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n\r\n    @media  only screen and (max-width: 500px) {\r\n        .button {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n</style>\r\n<body>\r\n<table class=\"wrapper\" style=\"background-color: #f8fafc\">\r\n    <tr>\r\n        <td align=\"center\">\r\n            <table class=\"content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n                <tr>\r\n                    <td class=\"header\" style=\"padding: 25px 0; text-align: center;\">\r\n                        <a href=\"#\" style=\"color: #bbbfc3; font-size: 19px; font-weight: bold; text-decoration: none; text-shadow: 0 1px 0 white;\">\r\n                            Восстановление доступа к аккаунту на сервере {SERVNAME}!\r\n                        </a>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td class=\"body\" width=\"100%\" style=\"background-color: #ffffff; border-bottom: 1px solid #edeff2; border-top: 1px solid #edeff2;\">\r\n                        <table class=\"inner-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; margin: 0 auto; width: 570px; -premailer-width: 570px;\">\r\n                            <tr>\r\n                                <td class=\"content-cell\" style=\"padding: 35px;\">\r\n                                    <h1 style=\"color: #3d4852; font-size: 19px; font-weight: bold; margin-top: 0; text-align: left;\">Отключение ограничения на вход по IP</h1>\r\n                                    <p>С айпи адреса {IP} был получен запрос на отключение ограничения входа с определенных IP на аккаунт <b>{LOGIN}</b></p>\r\n                                    <p>Ограничение было успешно отключено</p>                                    \r\n                                </td>\r\n                            </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td>\r\n                        <table class=\"footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; text-align: center; width: 570px;-premailer-width: 570px;\"><tr>\r\n                            <td class=\"content-cell\" align=\"center\" style=\"  padding: 35px;\">\r\n                                <p style=\"line-height: 1.5em; margin-top: 0; color: #aeaeae; font-size: 12px; text-align: center;\">© 2019 {SERVNAME}</p>\r\n                            </td>\r\n                        </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>', 5, 2, 'Письмо после сброса привязки аккаунта по IP в HTML формате\r\n	{IP} - IP адрес, с которого была заявка\r\n	{LOGIN} - логин аккаунта\r\n	{SERVNAME} - Название сервера'),
('rem_template', 'text', '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ru\">\r\n<head>\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n</head>\r\n<style type=\"text/css\">\r\n    body {\r\n        font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif, \'Apple Color Emoji\', \'Segoe UI Emoji\', \'Segoe UI Symbol\';\r\n        background-color: #f8fafc;\r\n        color: #74787e;\r\n        height: 100%;\r\n        hyphens: auto;\r\n        line-height: 1.4;\r\n        margin: 0;\r\n        -moz-hyphens: auto;\r\n        -ms-word-break: break-all;\r\n        width: 100% !important;\r\n        -webkit-hyphens: auto;\r\n        -webkit-text-size-adjust: none;\r\n        word-break: break-word;\r\n    }\r\n    p {\r\n        color: #3d4852; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;\r\n    }\r\n    table {\r\n        width: 100%;\r\n    }\r\n    table, td {\r\n        margin: 0; padding: 0;-premailer-cellpadding: 0; -premailer-cellspacing: 0; -premailer-width: 100%;\r\n        box-sizing: border-box;\r\n    }\r\n    @media  only screen and (max-width: 600px) {\r\n        .inner-body {\r\n            width: 100% !important;\r\n        }\r\n\r\n        .footer {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n\r\n    @media  only screen and (max-width: 500px) {\r\n        .button {\r\n            width: 100% !important;\r\n        }\r\n    }\r\n</style>\r\n<body>\r\n<table class=\"wrapper\" style=\"background-color: #f8fafc\">\r\n    <tr>\r\n        <td align=\"center\">\r\n            <table class=\"content\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n                <tr>\r\n                    <td class=\"header\" style=\"padding: 25px 0; text-align: center;\">\r\n                        <a href=\"#\" style=\"color: #bbbfc3; font-size: 19px; font-weight: bold; text-decoration: none; text-shadow: 0 1px 0 white;\">\r\n                            Восстановление доступа к аккаунтам на сервере {SERVNAME}!\r\n                        </a>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td class=\"body\" width=\"100%\" style=\"background-color: #ffffff; border-bottom: 1px solid #edeff2; border-top: 1px solid #edeff2;\">\r\n                        <table class=\"inner-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: #ffffff; margin: 0 auto; width: 570px; -premailer-width: 570px;\">\r\n                            <tr>\r\n                                <td class=\"content-cell\" style=\"padding: 35px;\">\r\n                                    <p>С айпи адреса {IP} был получен запрос на на восстановление данных от аккаунта по вашему E-Mail</p>\r\n                                    <p>Если Вы не запрашивали эту процедуру, просто проигнорируйте данное сообщение.</p><br><br>\r\n                                    <h3>Данные ваших аккаунтов:</h3>\r\n                                    {ACCOUNTS_DATA}\r\n                                </td>\r\n                            </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td>\r\n                        <table class=\"footer\" align=\"center\" width=\"570\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto; text-align: center; width: 570px;-premailer-width: 570px;\"><tr>\r\n                            <td class=\"content-cell\" align=\"center\" style=\"  padding: 35px;\">\r\n                                <p style=\"line-height: 1.5em; margin-top: 0; color: #aeaeae; font-size: 12px; text-align: center;\">© 2019 {SERVNAME}</p>\r\n                            </td>\r\n                        </tr>\r\n                        </table>\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>', 5, 2, 'Письмо восстановления данных аккаунтов в HTML формате\r\n	{IP} - IP адрес, с которого была заявка\r\n	{SERVNAME} - Название сервера\r\n	{ACCOUNTS_DATA} - данные аккаунтов с ссылками для восстановления доступа'),
('acc_data_template', 'text', '<table width=\"100%\" cellpadding=\"2\" cellspacing=\"0\" border=\"0\" align=\"center\" > \r\n  <tr> \r\n   <td width=\"120px\" align=\"right\" style=\"\"> <font color=\"#aa0000\">Логин:</font> </td> \r\n   <td align=\"left\" style=\"\"> <font color=\"#0000ff\">{LOGIN}</font> </td> \r\n  </tr> \r\n  <tr> \r\n   <td align=\"right\" style=\"\"> <font color=\"#aa0000\">Вопрос:</font> </td> \r\n   <td align=\"left\" style=\"\">{QUESTION}</td> \r\n  </tr> \r\n  <tr> \r\n   <td align=\"right\" style=\"\"> <font color=\"#aa0000\">Ответ:</font> </td> \r\n   <td align=\"left\" style=\"\">{ANSWER}</td> \r\n  </tr>                          \r\n</table>\r\n<p>Для сброса пароля на этом аккаунте, перейдите по ссылке <a href=\"{RESET_PASSW_LINK}\" target=\"_blank\" style=\"font-size:14px;text-decoration:underline;color:#1376C8;\">{RESET_PASSW_LINK}</a></p>\r\n<p>Для отключения ограничения входа с определенных IP/подсетей, перейдите по ссылке <a href=\"{RESET_IP_LINK}\" target=\"_blank\" style=\"font-size:14px;text-decoration:underline;color:#1376C8;\">{RESET_IP_LINK}</a></p>\r\n<br>', 5, 2, 'Текст данных аккаунта в HTML формате\r\n	{LOGIN} - логин аккаунта\r\n	{QUESTION} - Секретный вопрос\r\n	{ANSWER} - ответ на вопрос\r\n	{RESET_PASSW_LINK} - ссылка для сброса пароля на аккаунте\r\n	{RESET_IP_LINK} - ссылка для отключения запрета входа по IP на аккаунте'),
('test_mail_template', 'text', '<p>Если вы читаете данное письмо, значит настройки сделаны верно</p>', 5, 2, 'Текст тестового письма в HTML формате'),
('kaptcha_type', 'select', 'Internal,ReCaptcha v2,0', 6, 0, 'Тип капчи'),
('', 'desc', 'Параметры ReCaptcha v2', 6, 1, 'Получить данные <a href="https://www.google.com/recaptcha/admin#list" target="blank">можно тут</a>'),
('recaptcha2_site_key', 'string', '', 6, 1, 'Публичный ключ'),
('recaptcha2_secret_key', 'string', '', 6, 1, 'Секретный приватный ключ');

CREATE TABLE IF NOT EXISTS `skill_icons` (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(50) CHARACTER SET utf8 NOT NULL, `icon` blob NOT NULL, UNIQUE KEY `name` (`name`),  KEY `id` (`id`)) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
UPDATE `config` SET `group`=2 WHERE `name`='freekassa_merchant_id' OR `name`='freekassa_secret_word1' OR `name`='freekassa_secret_word2' OR `value`='Параметры сервиса Free-Kassa';
INSERT INTO `config` (`name`, `type`, `value`, `section`, `group`, `desc`) VALUES
('freekassa_new_version', 'bool', '0', 3, 2, 'Использовать ссылку для новой версии сайта freekassa.ru\r\nВыключить, если используется старый сайт free-kassa.ru');